# Generated by Django 2.1.dev20180313024248 on 2018-05-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTurnManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPlate', models.CharField(max_length=30)),
                ('timeIn', models.DateTimeField()),
                ('timeOut', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('timeIn', 'numberPlate'),
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberPlate', models.CharField(max_length=30)),
                ('timeIn', models.DateTimeField()),
            ],
            options={
                'ordering': ('timeIn', 'numberPlate'),
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('studentID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('faculty', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('kindOfTicket', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('expirationDate', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('studentID',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('numberPlate', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('numberPlate',),
            },
        ),
        migrations.AddField(
            model_name='student',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='StudentParking.Vehicle'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentParking.Student'),
        ),
        migrations.AddField(
            model_name='dailyturnmanagement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentParking.Student'),
        ),
    ]
