# Generated by Django 2.1.dev20180313024248 on 2018-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentParking', '0002_auto_20180515_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
